from setuptools import setup, find_packages

setup(
    name="MasterCSS",
    version="1.0.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    entry_points={"console_scripts": ["MasterCSS = MasterCSS.cli:main", ], },
    install_requires=[
        "pytest",
        "flask",
        "requests",
        "oauthlib",
        "pyOpenSSL",
        "sphinx",
        "Flask-Login",
        "Flask-SQLAlchemy",
        "Flask-Marshmallow",
        "python-dotenv",
        "marshmallow-sqlalchemy",
        "mysql-connector",
        "pymysql",
        "oauth2client",
        "google-api-python-client",
        "imutils",
        "paho-mqtt",
        "qrcode[pil]",
        "google-assistant-grpc==0.2.1",
        "google-auth-oauthlib>=0.1.0,<0.3",
        "urllib3[secure]>=1.21,<2",
        "sounddevice>=0.3.7,<0.4",
        "tenacity>=4.1.0,<5",
        "futures>=3.1.1,<4",
        "pathlib2>=2.3.0,<3",
        "click>=6.7,<7"
    ],
)
